php:
  'bullseye':
      - 7.3
      - 7.4
      - 8.0
      - 8.1
  'buster':
      - 7.3
      - 7.4
      - 8.0
      - 8.1

php-tag-format: '{{php_version}}-fpm-{{distro_version}}'

deps-packages:
  - default-mysql-client
  - gnupg2
  - locales-all
  - openssh-client

php-build-deps-packages:
  - autoconf
  - libbz2-dev
  - libfreetype6-dev
  - libgmp-dev
  - libicu-dev
  - libjpeg62-turbo-dev
  - libpng-dev
  - libpq-dev
  - libwebp-dev
  - libxml2-dev
  - libxpm-dev
  - libzip-dev

php-run-deps-packages:
  - libbz2-1.0
  - libfreetype6
  - libgmp10
  - libicu67
  - libjpeg62-turbo
  - libpng16-16
  - libwebp6
  - libxml2
  - libxpm4
  - libxslt1.1
  - libzip4
